# OpenF1 REST-Client
quarkus.rest-client.openf1.url=https://api.openf1.org
quarkus.rest-client.openf1.read-timeout=30000
quarkus.rest-client.openf1.connect-timeout=10000

# HTTP-Verbindung für langlaufende Season-Abfragen offen halten
quarkus.http.idle-timeout=10M

# Schema automatisch anlegen/aktualisieren, Cache überlebt Neustarts
quarkus.hibernate-orm.schema-management.strategy=update

# CORS, damit das Frontend zugreifen darf
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173,http://localhost:5174

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/f1analytics
quarkus.datasource.username=postgres
quarkus.datasource.password=Openf1
quarkus.http.port=8081
