# OpenF1 REST-Client
quarkus.rest-client.openf1.url=https://api.openf1.org

# Schema automatisch anlegen/aktualisieren, Cache überlebt Neustarts
quarkus.hibernate-orm.schema-management.strategy=update

# CORS, damit das Frontend (Port 5173) später zugreifen darf
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173